version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.4
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"   # si no hace falta exponer, sacá esta línea o usá "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
